# Generated by Django 4.1.5 on 2025-12-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='api_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
