# Generated by Django 4.1.5 on 2025-12-19 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_partido_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='numero_fecha',
            field=models.IntegerField(default=1),
        ),
    ]
