# Generated by Django 4.1.5 on 2025-12-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_partido_numero_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilempleado',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.empresa'),
        ),
    ]
