# Generated by Django 4.1.5 on 2025-12-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_perfilempleado_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='escudo_local',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='partido',
            name='escudo_visitante',
            field=models.URLField(blank=True, null=True),
        ),
    ]
