# Generated by Django 4.1.5 on 2025-12-24 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_partido_escudo_local_partido_escudo_visitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(editable=False, max_length=10, unique=True)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='torneos_creados', to=settings.AUTH_USER_MODEL)),
                ('participantes', models.ManyToManyField(related_name='torneos_participados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
